### ISSUE TITLE
Overflow warning

### ISSUE THREAD

**Issue by physikant** [regimantas/Oversampling#1]
I'm getting a warning when using this library:

C:\Users\...\Documents\Arduino\libraries\Oversampling\src\Oversampling.cpp: In member function 'int Oversampling::read(int)':
C:\Users\...\Documents\Arduino\libraries\Oversampling\src\Oversampling.cpp:55:23: warning: overflow in implicit constant conversion [-Woverflow]
     OversampleCount = 65536;

Being declared as int, OversampleCount cannot be 65536, but rather 65535. I'd suggest to reduce all the SampleCount specific OverSampleCounts by one and to adjust the range of the for loop instead within the Oversampling.ccp file:
```
for (int i=0; i<=OversampleCount; i++){
      TotalADC = TotalADC + analogRead(pin);
    }
```

**Comment by regimantas** [comment]
Thanks :)

**Comment by regimantas** [comment]
Fixed :)
